/**
 * Deterministic Mock Data for Trend Service
 * Used when the microservice is unavailable or ENABLE_TREND_SERVICE=false
 */

export const MOCK_COMBINED = {
  trendScores: {
    linen: 0.92,
    'oversized-blazer': 0.79,
    'pastel-denim': 0.66,
    'sustainable-fabrics': 0.87,
    athleisure: 0.58,
    'minimalist-accessories': 0.71,
    'wide-leg-pants': 0.64,
    'crop-tops': 0.55,
  },

  clusters: {
    meta: {
      n_clusters: 8,
      source: 'mock',
    },
    clusters: [
      {
        cluster_id: 0,
        category: 'tops',
        count: 1250,
        cluster_pop_score: 0.85,
        trend_score: 0.72,
        combined_score: 0.79,
        sample_indices: [12, 45, 89],
      },
      {
        cluster_id: 1,
        category: 'dresses',
        count: 980,
        cluster_pop_score: 0.78,
        trend_score: 0.88,
        combined_score: 0.82,
        sample_indices: [23, 67, 101],
      },
      {
        cluster_id: 2,
        category: 'shoes',
        count: 1100,
        cluster_pop_score: 0.82,
        trend_score: 0.65,
        combined_score: 0.73,
        sample_indices: [34, 78, 112],
      },
      {
        cluster_id: 3,
        category: 'outerwear',
        count: 750,
        cluster_pop_score: 0.65,
        trend_score: 0.79,
        combined_score: 0.71,
        sample_indices: [45, 89, 123],
      },
      {
        cluster_id: 4,
        category: 'accessories',
        count: 920,
        cluster_pop_score: 0.74,
        trend_score: 0.71,
        combined_score: 0.73,
        sample_indices: [56, 100, 134],
      },
      {
        cluster_id: 5,
        category: 'bottoms',
        count: 1050,
        cluster_pop_score: 0.80,
        trend_score: 0.64,
        combined_score: 0.72,
        sample_indices: [67, 111, 145],
      },
      {
        cluster_id: 6,
        category: 'activewear',
        count: 680,
        cluster_pop_score: 0.58,
        trend_score: 0.58,
        combined_score: 0.58,
        sample_indices: [78, 122, 156],
      },
      {
        cluster_id: 7,
        category: 'formal',
        count: 550,
        cluster_pop_score: 0.48,
        trend_score: 0.62,
        combined_score: 0.54,
        sample_indices: [89, 133, 167],
      },
    ],
  },

  combined: {
    clusters: [
      {
        cluster_id: 0,
        category: 'tops',
        cluster_pop_score: 0.85,
        trend_score: 0.72,
        combined_score: 0.79,
        sample_indices: [12, 45, 89],
      },
      {
        cluster_id: 1,
        category: 'dresses',
        cluster_pop_score: 0.78,
        trend_score: 0.88,
        combined_score: 0.82,
        sample_indices: [23, 67, 101],
      },
      {
        cluster_id: 2,
        category: 'shoes',
        cluster_pop_score: 0.82,
        trend_score: 0.65,
        combined_score: 0.73,
        sample_indices: [34, 78, 112],
      },
      {
        cluster_id: 3,
        category: 'outerwear',
        cluster_pop_score: 0.65,
        trend_score: 0.79,
        combined_score: 0.71,
        sample_indices: [45, 89, 123],
      },
      {
        cluster_id: 4,
        category: 'accessories',
        cluster_pop_score: 0.74,
        trend_score: 0.71,
        combined_score: 0.73,
        sample_indices: [56, 100, 134],
      },
      {
        cluster_id: 5,
        category: 'bottoms',
        cluster_pop_score: 0.80,
        trend_score: 0.64,
        combined_score: 0.72,
        sample_indices: [67, 111, 145],
      },
      {
        cluster_id: 6,
        category: 'activewear',
        cluster_pop_score: 0.58,
        trend_score: 0.58,
        combined_score: 0.58,
        sample_indices: [78, 122, 156],
      },
      {
        cluster_id: 7,
        category: 'formal',
        cluster_pop_score: 0.48,
        trend_score: 0.62,
        combined_score: 0.54,
        sample_indices: [89, 133, 167],
      },
    ],
    extra_trends: [
      {
        category: 'linen',
        trend_score: 0.92,
      },
      {
        category: 'oversized-blazer',
        trend_score: 0.79,
      },
      {
        category: 'pastel-denim',
        trend_score: 0.66,
      },
      {
        category: 'sustainable-fabrics',
        trend_score: 0.87,
      },
      {
        category: 'minimalist-accessories',
        trend_score: 0.71,
      },
      {
        category: 'wide-leg-pants',
        trend_score: 0.64,
      },
    ],
    generated_at: new Date().toISOString(),
  },

  demoProducts: {
    generated_at: new Date().toISOString(),
    products: [
      {
        id: 'demo-linen-0',
        title: 'Linen Summer Blouse',
        price: 89,
        image: null,
        sizeRecommendation: 'M',
        sizeConfidence: 85,
        returnRiskScore: 0.12,
        returnRiskLabel: 'low',
        trendCategory: 'linen',
        trendScore: 0.92,
      },
      {
        id: 'demo-oversized-blazer-1',
        title: 'Oversized Blazer Classic',
        price: 145,
        image: null,
        sizeRecommendation: 'L',
        sizeConfidence: 78,
        returnRiskScore: 0.18,
        returnRiskLabel: 'low',
        trendCategory: 'oversized-blazer',
        trendScore: 0.79,
      },
      {
        id: 'demo-pastel-denim-2',
        title: 'Pastel Denim Jacket',
        price: 125,
        image: null,
        sizeRecommendation: 'M',
        sizeConfidence: 82,
        returnRiskScore: 0.22,
        returnRiskLabel: 'low',
        trendCategory: 'pastel-denim',
        trendScore: 0.66,
      },
      {
        id: 'demo-sustainable-fabrics-3',
        title: 'Eco-Friendly Cotton Dress',
        price: 95,
        image: null,
        sizeRecommendation: 'S',
        sizeConfidence: 88,
        returnRiskScore: 0.10,
        returnRiskLabel: 'low',
        trendCategory: 'sustainable-fabrics',
        trendScore: 0.87,
      },
      {
        id: 'demo-minimalist-accessories-4',
        title: 'Minimalist Gold Necklace',
        price: 65,
        image: null,
        sizeRecommendation: 'One Size',
        sizeConfidence: 95,
        returnRiskScore: 0.15,
        returnRiskLabel: 'low',
        trendCategory: 'minimalist-accessories',
        trendScore: 0.71,
      },
      {
        id: 'demo-wide-leg-pants-5',
        title: 'Wide Leg Trousers',
        price: 110,
        image: null,
        sizeRecommendation: 'M',
        sizeConfidence: 80,
        returnRiskScore: 0.20,
        returnRiskLabel: 'low',
        trendCategory: 'wide-leg-pants',
        trendScore: 0.64,
      },
    ],
  },
};
